all:
  hosts:
    kubenode1:
      ansible_user: kubedeveloper
    kubenode2:
      ansible_user: kubedeveloper
    kubenode3:
      ansible_user: kubedeveloper
    kubenode4:
      ansible_user: kubedeveloper
